Repository cloudnode-pro/components, pull requests merged in 2024-10, with the labels that each got.

#1 Set up project, create base classes, and add CI
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .gitignore
  .idea/.gitignore
  .idea/components.iml
  .idea/modules.xml
  .idea/vcs.xml
  package-lock.json
  package.json
  src/Component.ts
  src/ElementComponent.ts
  src/SvgComponent.ts
  src/index.ts
  tsconfig.json
Labels: feature

#4 Add methods for setting component inner text and HTML content
  src/ElementComponent.ts
Labels: feature

#3 Create a package artifact to use in publish CI
  .github/workflows/ci.yml
Labels: bug

#5 Add documentation
  .github/workflows/ci.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  src/BaseComponent.ts
  src/Component.ts
  src/SvgComponent.ts
  src/index.ts
  typedoc.json
Labels: documentation

#6 Fix publish CI
  .github/workflows/ci.yml
Labels: enhancement

#7 Set path in which to download build artifact in publish CI
  .github/workflows/ci.yml
Labels: bug

#8 NPM provenance: fix repository URL
  package.json
Labels: bug

#12 Add select and selectAll shorthands
  src/Component.ts
Labels: feature

#15 Add method for setting CSS style on the current attribute
  src/Component.ts
Labels: feature

#16 Add a remove method to components.
  src/BaseComponent.ts
Labels: enhancement

#18 Prevent type expansion in docs
  src/BaseComponent.ts
  src/Component.ts
Labels: bug

#20 Add method to render component in the place of a slot
  src/NodeComponent.ts
Labels: feature

#26 Append HTML string literals with components
  src/DocumentComponent.ts
  src/ElementComponent.ts
  src/NodeComponent.ts
  src/TextComponent.ts
  src/index.ts
Labels: feature

#28 Allow `any` in HTML template literals
  src/DocumentComponent.ts
  src/ElementComponent.ts
Labels: feature

#29 Fix index access
  src/DocumentComponent.ts
Labels: bug
